# Generated by Django 6.0.7 on 2026-07-20 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_alter_athlete_athlete_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('supports_positions', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sports.sport')),
            ],
            options={
                'ordering': ['sport__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteSport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('started_playing', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_profiles', to='athletes.athlete')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athlete_profiles', to='sports.sport')),
                ('primary_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_profiles', to='sports.sportposition')),
            ],
            options={
                'ordering': ['-is_primary', 'sport__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='sportposition',
            constraint=models.UniqueConstraint(fields=('sport', 'name'), name='unique_position_name_per_sport'),
        ),
        migrations.AddConstraint(
            model_name='athletesport',
            constraint=models.UniqueConstraint(fields=('athlete', 'sport'), name='unique_sport_per_athlete'),
        ),
        migrations.AddConstraint(
            model_name='athletesport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('athlete',), name='one_primary_sport_per_athlete'),
        ),
    ]
