# Generated by Django 6.0.7 on 2026-07-21 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(help_text='Stable API key, for example goals or sprint_time_s.', max_length=60, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, and underscores only.', regex='^[a-z][a-z0-9_]*$')])),
                ('unit', models.CharField(default='count', help_text='For example count, metres, seconds, or percent.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_types', to='sports.sport')),
            ],
            options={
                'ordering': ['sport__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('sport', 'key'), name='unique_stat_key_per_sport')],
            },
        ),
    ]
