# Generated by Django 6.0.7 on 2026-07-21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0002_stattype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportFormat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("min_players_per_side", models.PositiveSmallIntegerField(default=1)),
                ("max_players_per_side", models.PositiveSmallIntegerField(default=1)),
                (
                    "has_teams",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "False for individual events such as athletics or "
                            "tennis singles."
                        ),
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sport__name", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="stattype",
            options={"ordering": ["sport__name", "display_order", "name"]},
        ),
        migrations.AddField(
            model_name="stattype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stattype",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="stattype",
            name="short_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stattype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stattype",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Integer"),
                    ("DECIMAL", "Decimal"),
                    ("BOOLEAN", "Boolean"),
                ],
                default="INTEGER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stattype",
            name="unit",
            field=models.CharField(
                blank=True,
                default="count",
                help_text="For example count, metres, seconds, or percent.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sportformat",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formats",
                to="sports.sport",
            ),
        ),
        migrations.AddConstraint(
            model_name="stattype",
            constraint=models.UniqueConstraint(
                fields=("sport", "name"),
                name="unique_stat_name_per_sport",
            ),
        ),
        migrations.AddConstraint(
            model_name="stattype",
            constraint=models.UniqueConstraint(
                fields=("sport", "short_name"),
                name="unique_stat_short_name_per_sport",
            ),
        ),
        migrations.AddConstraint(
            model_name="sportformat",
            constraint=models.UniqueConstraint(
                fields=("sport", "name"),
                name="unique_format_name_per_sport",
            ),
        ),
    ]
