# Generated by Django 6.0.7 on 2026-07-20 16:27

import athletes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(default=athletes.models.generate_athlete_id, editable=False, max_length=20, unique=True),
        ),
    ]
