# Generated by Django 6.0.7 on 2026-07-21 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_alter_athlete_athlete_id'),
        ('sports', '0002_stattype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='For example, Nairobi Youth Cup — Final.', max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CHECK_IN_OPEN', 'Check-in Open'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='sports.sport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_participations', to='athletes.athlete')),
                ('athlete_sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_participations', to='sports.athletesport')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.game')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_participations', to='sports.sportposition')),
            ],
        ),
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(default='full_game', help_text='For example full_game, first_half, q1, or set_1.', max_length=50)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='games.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='games.gameparticipant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_game_stats', to=settings.AUTH_USER_MODEL)),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_stats', to='sports.stattype')),
            ],
        ),
        migrations.CreateModel(
            name='GameVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('SELF', 'Self Confirmation'), ('INDEPENDENT_RECORDER', 'Independent Recorder'), ('COACH', 'Coach Verified'), ('SCOUT', 'Scout Verified'), ('OFFICIAL', 'Official Event')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='games.game')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('game', 'athlete'), name='unique_athlete_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gamestat',
            constraint=models.UniqueConstraint(fields=('participant', 'stat_type', 'period'), name='unique_stat_per_participant_period'),
        ),
    ]
