# Generated by Django 6.0.7 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def migrate_game_formats(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    SportFormat = apps.get_model("sports", "SportFormat")

    for game in Game.objects.select_related("sport").all().iterator():
        name = (game.format or "").strip() or "Standard"
        sport_format, _ = SportFormat.objects.get_or_create(
            sport_id=game.sport_id,
            name=name,
            defaults={"has_teams": True},
        )
        game.format_reference_id = sport_format.id
        game.save(update_fields=["format_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("sports", "0003_sportformat_alter_stattype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestat",
            name="boolean_value",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="value",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="format_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sports.sportformat",
            ),
        ),
        migrations.RunPython(migrate_game_formats, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="game",
            name="format",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="format_reference",
            new_name="format",
        ),
        migrations.AlterField(
            model_name="game",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="sports.sportformat",
            ),
        ),
    ]
